//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	enum ArmorType
	{
		Head,
		Shoulder,
		Chest,
		Wrist,
		Hands,
		Legs,
		Feets
	}
	
	public class ArmorItem : CharacterItem
	{
		ArmorType type;
		ValueRange value;
		int weight;
		string name;
	}
	
	
	public class LeatherChest : ArmorItem
	{
		public LeatherChest ()
		{
			type = AssemblyCSharp.ArmorType.Chest;
			value = new ValueRange (2, 2);
			name = "Leather chest";
		}
	}
	public class LeatherShoulder : WeaponItem
	{
		public LeatherShoulder ()
		{
			type = AssemblyCSharp.ArmorType.Shoulder;
			value = new ValueRange (2, 2);
			name = "Leather shoulderpads";
		}
	}

	public class LeatherHead : ArmorItem
	{
		public LeatherHead ()
		{
			type = AssemblyCSharp.ArmorType.Head;
			value = new ValueRange (2, 2);
			name = "Leather chest";
		}
	}

	public class LeatherWrist: ArmorItem
	{
		public LeatherWrist ()
		{
			type = AssemblyCSharp.ArmorType.Wrist;
			value = new ValueRange (2, 2);
			name = "Leather chest";
		}
	}

	public class LeatherFeet: ArmorItem
	{
		public LeatherFeet ()
		{
			type = AssemblyCSharp.ArmorType.Feet;
			value = new ValueRange (2, 2);
			name = "Leather chest";
		}
	}


}

