//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum WeaponType
	{
		OneHanded,
		TwoHanded
	}

	public class WeaponItem : CharacterItem
	{
		public WeaponType type;
		public ValueRange value;
		public string name;
	}


	public class ShortSword : WeaponItem
	{
		public ShortSword ()
		{
			type = AssemblyCSharp.WeaponType.OneHanded;
			value = new ValueRange (1, 6);
			name = "Short Sword";
		}
	}
	public class WoodStaff : WeaponItem
	{
		public WoodStaff ()
		{
			type = AssemblyCSharp.WeaponType.TwoHanded;
			value = new ValueRange (2, 8);
			name = "Wooden staff";
		}
	}
}

