//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class ValueRange
	{
		public int min;
		public int max;
		private Random mRandom;
		public ValueRange(int min,int max)
		{
			this.min = min;
			this.max = max;
			mRandom = new Random ();
		}
		public override string ToString()
		{
			return(String.Format("min:{0} + max:{1}", min, max));
		}

		public int GetValue()
		{

			return mRandom.Next (min, max);
		}

//		public static int operator =(ValueRange vr) 
//		{
//			return int(vr.GetValue());
//		}
	}


	public interface CharacterItem
	{

	}

	public class ShieldItem : CharacterItem
	{

	}





	public class CharacterData
	{
		public int Strength;
		public int Agility;
		public int Stamina;
		public int Intelligence;
		public int Charisma;
		public int Toughness;
		public int Armor;
		public int Spirit;

		public List<WeaponItem> Weapons;
		public List<ArmorItem> Armors;
		public List<ShieldItem> Shield;

		public List<CharacterItem> BagItems;

		public CharacterData ()
		{



		}

		public void AddBagItem(CharacterItem ci)
		{
			BagItems.Add (ci);
		}

		public void LoadCharacter()
		{
			Strength = 10;
			Agility = 10;
			Stamina = 10;
			Intelligence = 10;
			Charisma = 10;
			Toughness = 10;
			Armor = 10;
			Spirit = 10;

		}
	}
}

